stages:
  - build
  - test

before_script:
  - if [[ -z ${CI_COMMIT_TAG} ]]; then export TAG=${CI_COMMIT_SHA:0:8}; else export TAG=${CI_COMMIT_TAG}; fi

build_image:
  stage: build
  tags:
    - repo
  script:
    - docker build -t $REPO_URL/$APP_NAME:${TAG} .

puch_image:
  stage: build
  tags:
    - repo
  script:
    - docker push $REPO_URL/$APP_NAME:${TAG}
    
rspec:
  stage: test
  only:
    - master
    - develop2
  tags:
    - repo
  script:
    - ls -l
