stages:
  - build
  - rspec
  - rubocop

before_script:
  - if [[ -z ${CI_COMMIT_TAG} ]]; then export TAG=${CI_COMMIT_SHA:0:8}; else export TAG=${CI_COMMIT_TAG}; fi

build_image:
  stage: build
  tags:
    - repo
  script:
    - docker build -t $REPO_URL/$APP_NAME:${TAG} .

push_image:
  stage: build
  tags:
    - repo
  script:
    - docker push $REPO_URL/$APP_NAME:${TAG}

test:
  stage: rspec
  image: 
    name: $REPO_URL/$APP_NAME:01fd1c46
  only:
    - master
    - develop2
  tags:
    - test
  variables:
    CC_LOG_LEVEL: unknown
    CC_DB_NAME: case_core
    CC_DB_HOST: localhost
    CC_DB_USER: rkis
    CC_DB_PASS: 123456
  script:
    - env

