stages:
  

build_with_tag:
  stage: build
  only:
    - tags
  tags:
  - repo
  script:
    - docker build -t $REPO_URL/$APP_NAME:${CI_COMMIT_TAG} .
    - docker push $REPO_URL/$APP_NAME:${CI_COMMIT_TAG}

build_without_tag:
  stage: build
  except:
    - tags
  tags:
    - repo
  script:
    - docker build -t $REPO_URL/$APP_NAME:${CI_COMMIT_SHA:0:8} .
    - docker push $REPO_URL/$APP_NAME:${CI_COMMIT_SHA:0:8}
