---
- name: Проверить есть ли приложение в каталоге
  uri:
    url: 'https://{{ docker_private_registry_url }}/v2/_catalog'
    validate_certs: no
    method: GET
    body_format: json
  register: catalog_response

- name: Пробразовать список репозиториев приложений
  set_fact:
    catalog: "{{ catalog_response['json']['repositories'] | list }}"

- name: Ensure image not in registry
  uri:
    url: 'https://{{ docker_private_registry_url }}/v2/{{ app_name }}/tags/list'
    validate_certs: no
    method: GET
    body_format: json
  register: tags_response
  when: app_name in catalog

- name: Преобразовать список тегов приложения
  set_fact:
    tags: "{{ tags_response['json']['tags'] | list }}"
  when: tags_response['json']['tags'] is defined

- name: Push the image if it's not already in registry
  shell: 'docker push {{ docker_private_registry_url }}/{{ app_name }}:{{ docker_image_tag }}'
  when: docker_image_tag not in tags
