---
- hosts: local
  become: yes

  pre_tasks:
    - name: "Set environment variables"
      lineinfile:
        dest: "/home/vagrant/.bashrc"
        regexp: "^export {{ item.var }}="
        line: "export {{ item.var }}={{ item.value }}"
      with_items:
        - { var: "PGUSER", value: "user_case_core"}
        - { var: "PGDATABASE", value: "case_core"}
        - { var: "RACK_ENV", value: "development" }

  tasks:
    - name: "Create database"
      postgresql_db:
        name: case_core
        encoding: UTF-8

    - name: "Create user for database"
      postgresql_user:
        db: case_core
        name: user_case_core
        encrypted: no
        password: 123456
        priv: "ALL"
        role_attr_flags: "SUPERUSER"

    - name: "Create hstore for database"
      postgresql_ext:
        db: case_core
        name: hstore
          
    - name: "Create pg_trgm for database"
      postgresql_ext:
        db: case_core
        name: pg_trgm
