---
app_env: preprod

docker_run_variables:
  RACK_ENV: production
  RCM_DB_USER: user_case_manager
  RCM_DB_PASS: daEvfin
  RCM_DB_HOST: pgsql.preprod.rk.local
  RCM_DB_NAME: case_manager
  RCM_LOG_LEVEL: info
  RCM_BIND_HOST: 0.0.0.0
  RCM_PORT: 7070
  RCM_STOMP_HOST: 10.33.68.207
  RCM_STOMP_PORT: 61613
  RCM_STOMP_SUBSCRIBE_TO: 'smev3.response.queue'
  RCM_STOMP_SEND_TO: 'smev3.queue'
  RCM_STOMP_SMEV2_INPUT_QUEUE: 'smev2.response.queue'
  RCM_STOMP_SMEV2_OUTPUT_QUEUE: 'dispatch.queue'
  VIRTUAL_HOST: case-manager.preprod.rk.local
  VIRTUAL_PORT: 7070
  SMRC_HOST: smev3rc.preprod.rk.local
  SMRC_PORT: 8066

docker_run_labels:
  app_name: '{{ app_name }}'
  app_env: '{{ app_env }}'
  app_url: '{{ docker_run_variables["VIRTUAL_HOST"] }}'
